#!/bin/bash

TABLE=$1
if [ $# -eq 0 ]
  then
    DB="test"
  else
    DB=$2
fi

# echo `mongorestore --drop -d ${DB} -c ${TABLE} db/${TABLE}.bson`
echo `mongoimport --db ${DB} --collection ${TABLE} --type json --file tools/db/${TABLE}.json --jsonArray --drop`